language: python
python:
  - "2.7"
# Apply only on main branches
branches:
  except:
       - /^feature.*$/

# command to install Ubuntu dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip python-numpy python-matplotlib python-biopython
  
  - wget https://github.com/hyattpd/Prodigal/archive/v2.6.2.tar.gz
  - tar -xf v2.6.2.tar.gz
  - cd Prodigal-2.6.2 && make && sudo make install
  
  - wget  http://eddylab.org/software/infernal/infernal-1.1.2.tar.gz
  - tar -xf infernal-1.1.2.tar.gz
  - cd infernal-1.1.2 && ./configure && make && sudo make install
  
  - wget  http://eddylab.org/software/hmmer3/3.1b2/hmmer-3.1b2.tar.gz
  - tar -xf hmmer-3.1b2.tar.gz
  - cd hmmer-3.1b2 && ./configure && make && sudo make install
  - cd -

# command to run tests
script:
- python setup.py sdist
- pip install sdist/integron_finder*.tar.gz
- python tests/run_tests.py -vv

